{% set name = "xformers" %}
{% set version = "0.0.29.post1" %}
#cuda_version: ${{ env.get("CONDA_OVERRIDE_CUDA", default="None")}}
{% set cuda_version = "12" %}
# cuda: ${{ "true" if cuda_version != "None" else "false" }}
#cuda_build_string: cuda_${{ cuda_version }}
{% set cuda_build_string = "cuda_12" %}
# ${{ cuda_build_string if cuda ==  "true" else "cpu_" }}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/x/xformers/xformers-{{ version }}.tar.gz
    sha256: d78c256e4c24ecc00f6f374d5b96afd0b56b3fb197f02d9efff4357fd5a399b4
  - url: https://raw.githubusercontent.com/NVIDIA/cutlass/main/LICENSE.txt
    sha256: 6fc6ad419e4d26571a14c7c4d26b65345865c20dd8686ddcf5e8673f54d3d233
    file_name: third_party/cutlass/LICENSE.txt
  - url: https://raw.githubusercontent.com/Dao-AILab/flash-attention/main/LICENSE
    sha256: 8c9ccb96c065e706135b6cbad279b721da6156e51f3a5f27c6b3329af9416d73
    file_name: third_party/flash-attention/LICENSE

build:
  number: 0
  skip: True # [win]
  script_env:
    - cuda_compiler_version={{ cuda_version | default('None') }}
    - package_version={{ version }}

requirements:
  build:
    - python
    - pytorch >=2.4

    #- cuda-driver-dev
    #- cuda-cudart-dev
    #- cuda-nvrtc-dev
    #- cuda-nvtx-dev
    #- cuda-nvml-dev
    #- libcublas-dev
    #- libcufft-dev
    #- libcurand-dev
    #- libcusolver-dev
    #- libcusparse-dev

    - {{ compiler('cxx') }}
    - git

    #- {{ compiler('cuda') }}
    #- cuda-version =={{ cuda_version }}

  host:
    - wheel
    - python
    - pip
    - setuptools
    - {{ "pytorch * cpu*" }}
    - pytorch >=2.4

    #- cuda-version =={{ cuda_version }}

    #- cuda-driver-dev
    #- cuda-cudart-dev
    #- cuda-nvrtc-dev
    #- cuda-nvtx-dev
    #- cuda-nvml-dev
    #- libcublas-dev
    #- libcufft-dev
    #- libcurand-dev
    #- libcusolver-dev
    #- libcusparse-dev

  run:
    - python
    - numpy
    - pyre-extensions >=0.0.29
    - {{ "pytorch * cpu*" }}

  ignore_run_exports:
    # not identical to list of host deps; we do need cuda-cudart,
    # cuda-driver-dev & cuda-nvml-dev have no run-exports
    #- cuda-nvrtc-dev
    #- cuda-nvtx-dev
    #- libcublas-dev
    #- libcufft-dev
    #- libcurand-dev
    #- libcusolver-dev
    #- libcusparse-dev

test:
  requires:
    - pip
  imports:
    - xformers
  commands:
    - pip check
#$  - script:
#      - python -m xformers.info

about:
  license: BSD-3-Clause AND Apache-2.0
  license_family: BSD
  license_file:
    - LICENSE
    - third_party/cutlass/LICENSE.txt
    - third_party/flash-attention/LICENSE
    - third_party/sputnik/LICENSE
  summary: "XFormers: A collection of composable Transformer building blocks."
  home: https://facebookresearch.github.io/xformers/
  description: "xFormers is a PyTorch based library which hosts flexible Transformers parts"
  dev_url: https://github.com/facebookresearch/xformers
  doc_url: https://facebookresearch.github.io/xformers/

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/49522
    reason: Dependency for vllm
    recipe-maintainers:
      - bkreider
  recipe-maintainers:
    - jan-janssen
    - h-vetinari
